### ISSUE TITLE
Unable to install via packagist: no git tags

### ISSUE THREAD

**Issue by fredden** [mateussantin/magento2-admin-order-status-color#2]
This looks like a great addition to Magento. Thanks for making this and making it available publicly.

Please can you create some `git` tags in this repository so that it can be installed via composer. I'd like to install this on a Magento website, but am currently getting an error saying that no stable versions are available. It looks like you've [specified a 'version' in `composer.json`](https://github.com/mateussantin/magento2-admin-order-status-color/blob/dc9987adf8be6c737eb74b6403fce82e8c95a008/composer.json#L7), but there is no [corresponding tag in `git`](https://github.com/mateussantin/magento2-admin-order-status-color/tags) (or maybe only the copy on GitHub? `git push --tags`) so I get the following error when attempting to install.

![Screenshot_2022-09-23_10-48-15](https://user-images.githubusercontent.com/334786/191935186-3e6206dd-d91f-40d3-b8ac-56a091dcfcf8.png)

There are no available versions currently listed on https://packagist.org/packages/mateus/module-orderstatuscolor

See also https://getcomposer.org/doc/02-libraries.md#library-versioning

**Comment by fredden** [comment]
@mateussantin is there anything that I can do to help get this fixed? I'd like to start using this module, but cannot install it via composer yet.

**Comment by mateussantin** [comment]
@fredden  Hello all right? you can install with this alternative code if you can't, I tested it here and it's ok.
`composer require mateus/module-orderstatuscolor:dev-master`

**Comment by fredden** [comment]
@mateussantin thanks for the offer of how to install without a version number. I'm aware of how composer and versioning works.
I'll wait for this issue to be fixed before adding it to our list of "install everywhere" modules.

**Comment by almeidarobertop** [comment]
Hello @mateussantin . Your module is released awhile already and looks like no critical issues has been found. Could you release a stable tag for the module to be installed on projects with that restriction?

![image](https://github.com/mateussantin/magento2-admin-order-status-color/assets/86005553/7fd44913-a17b-44df-810f-dde5d3866576)
![image](https://github.com/mateussantin/magento2-admin-order-status-color/assets/86005553/42c3d4be-e31b-4789-a49c-ebe9559834be)

**Comment by almeidarobertop** [comment]
Hello @mateussantin . We've forked your project to try to contribute, but TAGs won't be shared via Pull Requests. So, I would advise you to do yourself, by applying the following commands:

> git tag -a 1.0.0 HEAD
> git push origin 1.0.0

If you decide to do this, share with us once done, to allow us to import your module to our project.
Best regards.

**Comment by mateussantin** [comment]
Hi @almeidarobertop, I released a 2.0.0 tag, you can use it if you prefer.

**Comment by almeidarobertop** [comment]
@mateussantin thank you man. This update resolves this issue. I believe you may close this one :)

**Comment by fredden** [comment]
Thanks @mateussantin and @almeidarobertop.
